version: '3.1'

services:
  db:
    container_name: postgres-db
    image: postgres:14.2
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-data:/var/lib/mysql

volumes:
  postgres-db-data:
    external: true