spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

### LOGGING ###
logging:
  level:
    root: info

jwt:
  secret: yourSecretHere
  expiration: 86400000
